version: '3.8'

services:
  # PostgreSQL Database for Authentication
  postgres-auth:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      # - 'PGDATA=/data/postgres'
    volumes:
      - ./postgres/auth:/data/postgres
    ports:
      - "5432:5432"
    restart: always